### PR TITLE
np negative power

### PR DESCRIPTION
**Pull request by pencoa**
When I run the code, np.power does not support negative values. So I modify it.

### CODE REVIEW

**Comment by tkipf** [comment]
Thanks. It seems there are some extra files in your PR. Please remove these
other changes or add comments if you want your PR to be considered for
merging.

Looking at the documentation of `np.power` it looks like the issue is not
the negative exponent, but rather the `dtype` of the argument. This can be
fixed by simply replacing `np.array(mx.sum(1))` with `np.array(mx.sum(1),
dtype=np.float32)`.

**Comment by pencoa** [comment]
soga. so that is it. 
If you place train.py and model.py in the pygcn directory, it can not import properly.
```
  File "pygcn/train.py", line 12, in <module>
    from pygcn.utils import load_data, accuracy
ModuleNotFoundError: No module named 'pygcn'
```
So I remove pygcn. prefix and run train.py in pygcn directory.

**Comment by pencoa** [comment]
BTW, I found a repository generate Orthogonal Polynomials
https://github.com/Orcuslc/OrthNet.git

**Comment by wbadart** [comment]
How are you running the training script? On my machine, I can duplicate your error by feeding the script directly to python (i.e. `$ python pygcn/train.py`) but invoking it as a runnable module works just fine: `$ python -m pygcn.train`.

**Comment by pencoa** [comment]
> How are you running the training script? On my machine, I can duplicate your error by feeding the script directly to python (i.e. `$ python pygcn/train.py`) but invoking it as a runnable module works just fine: `$ python -m pygcn.train`.

Yeah, I run as `$ python pygcn/train.py` and never try `$ python -m pygcn.train` before. Thank you.

**Pull request closed without merging**
